spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: Dsskl101@


jwt:
  secret: secreto_curso_kotlin